### PR TITLE
PyTorch-Ignite server request

### PR DESCRIPTION
**Pull request by vfdev-5**
Hi Andy,

As discussed in the email, I create a request here for AWS credits for PyTorch-Ignite project. 

Thanks,
Victor

### CODE REVIEW

**Comment by vfdev-5** [comment]
Hi Andy (@aterrel) can we proceed further with this request ?

**Comment by aterrel** [comment]
Oh shoot I'm terribly sorry. Let me get that moved forward.

**Comment by vfdev-5** [comment]
Thanks Andy :)

**Comment by aterrel** [comment]
Okay your account is created, I used the name vfdev-5 but let me know if you need a different name. I sent you the access credentials via the NumFOCUS Slack. Let me know if there is a better way to send them.

**Comment by aterrel** [comment]
Also please make sure you attribute AWS in a blog or release. I have to file a report before Jun 2021 and need to show the impact their donation makes.

**Pull request merged**
